var Router = require("routes-router")

module.exports = function createRouter(handler) {
  var router = Router()
  router.addRoute("/", handler.dataTable.bind(handler))
  router.addRoute("/api/session", handler.session.bind(handler))
  router.addRoute("/api/login", handler.login.bind(handler))
  router.addRoute("/api/logout", handler.logout.bind(handler))
  router.addRoute("/api/pull", handler.pull.bind(handler))
  router.addRoute("/api/push", handler.push.bind(handler))
  router.addRoute("/api/changes", handler.changes.bind(handler))
  router.addRoute("/api/stats", handler.stats.bind(handler))
  router.addRoute("/api/bulk", handler.bulk.bind(handler))
  router.addRoute("/api/metadata", handler.package.bind(handler))
  router.addRoute("/api/manifest", handler.manifest.bind(handler))
  router.addRoute("/api/rpc", handler.rpc.bind(handler))
  router.addRoute("/api/csv", handler.exportCsv.bind(handler))
  router.addRoute("/api", handler.hello.bind(handler))
  router.addRoute("/api/rows", handler.document.bind(handler))
  router.addRoute("/api/rows/:key", handler.document.bind(handler))
  router.addRoute("/api/rows/:key/:filename", handler.blob.bind(handler))
  router.addRoute("/api/blobs/:key", handler.blobs.bind(handler))
  router.addRoute("*", handler.notFound.bind(handler))
  return router
}